http:
  port: "8081"
  
american:
  host: "training4-american-api-gm.us-e2.cloudhub.io"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  client_id: "a0d865f457974a4883a34e2f6986cad1"
  client_secret: "bfC0e012a8d545C798617b6F4C6B1668"
 
training:
  host: "ilt.learn.mulesoft.com"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
 
delta:
  wsdl: "http://ilt.learn.mulesoft.com/delta?wsdl"
  service: "TicketServiceService"
  port: "TicketServicePort"